language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gdebi-core
  - sudo test/travis/build_deps.sh precise $TRAVIS_BUILD_DIR
script: ./test/travis/build_travis.sh
branches:
  only:
    - 'master'
    - '/feature.*/'
    - '/^4\.[0-9]+$/'
notifications:
  email:
    recipients:
      - gled@remote-shell.net
    on_success: never
    on_failure: always
